%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Users\ediso\Desktop\Technical Projects\MatlabProcessing\DataProcessed\Transition_data_imputed_rf.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 14-Oct-2022 18:25:35

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 59);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:BG48946";

% Specify column names and types
opts.VariableNames = ["Sheet", "Time", "RECORD", "BattV_Avg", "R_Real_Power", "R_Real_Power_kW", "R_Frequency", "R_Voltage", "R_Amperage", "R_Power_Factor", "R_Power_VI", "R_Power_VI_kW", "R_Power_VI_PF", "R_Power_VI_PF_kW", "Y_Real_Power", "Y_Real_Power_kW", "Y_Frequency", "Y_Voltage", "Y_Amperage", "Y_Power_Factor", "Y_Power_VI", "Y_Power_VI_kW", "Y_Power_VI_PF", "Y_Power_VI_PF_kW", "B_Real_Power", "B_Real_Power_kW", "B_Frequency", "B_Voltage", "B_Amperage", "B_Power_Factor", "B_Power_VI", "B_Power_VI_kW", "B_Power_VI_PF", "B_Power_VI_PF_kW", "Gen_Cur_R", "Gen_Cur_Y", "Gen_Cur_B", "R_Gen_VI", "R_Gen_VI_kW", "R_Gen_VIPF", "R_Gen_VIPF_kW", "Y_Gen_VI", "Y_Gen_VI_kW", "Y_Gen_VIPF", "Y_Gen_VIPF_kW", "B_Gen_VI", "B_Gen_VI_kW", "B_Gen_VIPF", "B_Gen_VIPF_kW", "Total_Load_Real_Power", "Total_Load_Real_Power_kW", "Load_VI", "Load_VI_kW", "Load_VIPF", "Load_VIPF_kW", "Total_Gen_VI", "Total_Gen_VI_kW", "Total_Gen_VIPF", "Total_Gen_VIPF_kW"];
opts.VariableTypes = ["double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties


% Import the data
transition_data_imputed = readtable("D:\Users\ediso\Desktop\Technical Projects\MatlabProcessing\DataProcessed\Transition_data_imputed_rf.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts